---
title: "Lab 1: Intro to R and data analysis"
subtitle: "<span class='code'>2024-07-24</span>"
#date: "2024-07-24"
tbl-colwidths: [5,20,75]
## ------  general Output Options
execute:     
  eval: true
  echo: false     #  include source code in output
  warning: false  #  include warning code in output
  error: false    #  include error code in output
  output: false   # include output code in output (CHG in BLOCKS)
  # include: false   # R still runs but code and results DON"T appear in output  
  cache: false # normalmnte false
## ------  parameters (for disclorsure or not of files)
params:
  src_slide_file: "slides_lab01.html" # default value (placeholder slide)
  lab_R_code: "lab01_code.R"          # default value (placeholder R code)
---

```{r}

# This param is not in r, so I will use: `r params$src_slide_file`
src_slide_file <- c("slides_lab00.html", # default closed 
                    "slides_lab01.html",
                    "slides_lab02.html",
                    "slides_lab03.html",
                    "slides_lab04.html")

# This param is  in r, so I will use:   params$lab_R_code
lab_R_code <- c("lab00_code.R",
                "lab01_code.R",
                "lab02_code.R" ,
                "lab03_code.R" ,
                "lab04_code.R")

params$src_slide_file
```


<!-- 1/2 DIAPOSITIVA WIDE (16:9) -->
```{=html}
<iframe class="slide-deck" src= `r params$src_slide_file` height="420" width="747" style="border: 1px solid #2e3846;"></iframe>
```

<!-- <!-- 2/2 DIAPOSITIVA STD (4:3) -->
<!-- ```{=html} -->
<!-- <iframe class="slide-deck" src= params$src_slide_file height="420" width="565" style="border: 1px solid #2e3846;"></iframe> -->
<!-- ``` -->

<a href=`r params$src_slide_file` target="_blank">View slides in full screen</a>



\pagebreak

```{r}
#| eval: true
#| echo: false
#| output: true

library(downloadthis)
```

{{< pagebreak >}}

## Practice session 1: input data (as `subfolder`)

```{r}
#| eval: true
#| echo: false
#| output: true

download_dir(
  path = here::here("practice", "data_input", "01_datasets"),
  output_name = "labs input data",
  button_label = "Download input data 1",
  button_type = "success",
  has_icon = TRUE,
  icon = "fa-solid fa-folder-open",
  self_contained = FALSE
)
```


## Practice session 1: R code (as `.R` file)
```{r}
#| echo: false
#| eval: true
#| output: true

library(fs) 

# using a param for which file 
download_file(
  path =  here::here("practice", "Rcode", params$lab_R_code ), # param
  output_name = fs::path_ext_remove ( params$lab_R_code), # param + no extension.... 
  output_extension = ".R",  
  button_label = "Download Lab session 1 as .R file",
  button_type = "primary",
  has_icon = TRUE,
  icon = "fa-brands fa-r-project",
  self_contained = FALSE
)
```
