project:
  type: website
  output-dir: docs # to publish website on GithubPages
  render:
    - "*.qmd"
    - "!R_stuff/"
    - "!zzz_old"

execute:
  freeze: auto  # Re-render only when source changes

# bibliography: files/bib/references.bib
# csl: files/bib/chicago-author-date.csl

website:
  title: "R 4 biostats"
  description: "Code and supplementary materials for the ...."
  site-url: "https://lulliter.github.io/R4biostats"
  # repo-url: "https://github.com/Lulliter/rassegna"
  favicon: images/icons8_hist_96.png
  page-footer:
    left: |
      {{< fa brands creative-commons >}} 2024 M. Chiara Mimmi<br>
      License {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}} {{< fa brands creative-commons-sa >}}
      [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View source at {{< fa brands github >}} GitHub](https://github.com/Lulliter/R4biostats)

  page-navigation: true
  
  navbar:
    pinned: true # non si muove quando scorro la pagina 
    background: "#72aed8" # "#0084e6" "#EE6A24"
    right:
      - text: "Home"
        icon: house-fill # https://icons.getbootstrap.com/?q=home
        href: index.qmd
      - text: "Pre-Workshop"
        icon: code-square # https://icons.getbootstrap.com/?q=home
        href: install.qmd
      - text: "Materials"
        icon: archive-fill # https://icons.getbootstrap.com/?q=home
        href: materials.qmd
      - text: "About"
        icon: file-earmark-person-fill # https://icons.getbootstrap.com/?q=home
        href: about.qmd

  # sidebar:
  #   - id: install
  #     contents:
  #       - install.qmd
  #   - id: materials
  #     title: "Materials"
  #     style: "docked"
  #     contents:
  #         - materials/index.qmd
  #         - materials/1-Day-1/index.qmd
  #         - materials/2-Day-2/index.qmd
  #   - id: about
  #     contents:
  #       - about.qmd

format:
  html:
    toc: true
    toc-location: "left"
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    mainfont: "Lato"
    monofont: "Fira Mono"
    footnotes-hover: true
    fontsize: 1em
    theme: theme/my-litera.scss
    css: theme/styles.css
    highlight-style: monokai



