---
title: "Intro to Biostatistics with R"
subtitle: "15-18 of July, 2024"
execute:     
  eval: true
  echo: false     #  include source code in output
  warning: false  #  include warning code in output
  error: false    #  include error code in output
  output: true   # include output code in output (CHG in BLOCKS)
  # include: false   # R still runs but code and results DON"T appear in output  
  cache: false # normalmnte false
fig-cap-location: top
tbl-cap-location: top

---


::: {.callout-caution collapse="false"}
Website constrution in progress...
:::


# Welcome! 

This website collects the materials for a four day workshop organized by [MITGEST Doctoral Network](https://www.mitgest.eu/) in July 2024, hosted by the Radboud Center for Mitochondrial Medicine, Nijmegen, Netherlands.

- [Location:]{.smallcaps} Radboud Center for Mitochondrial Medicine, xxxxx Nijmegen, Netherland
- [Time:]{.smallcaps} 9 am - 5 pm July 24^th^ to July 27^th^, 2024


# Workshop Overview

This Biostatistics workshop provides an introduction to selected topics in biostatistical concepts and reasoning. 
This course aims to introduce to the field and gives a solid understanding of data and data types, statistical inference and survey design applied to life sciences. 

Specific topics covered include: tools for describing central tendency and variability in data; methods for performing inference on population means and proportions via sample data; statistical hypothesis testing and its application to group comparisons; issues of power and sample size in study designs; elements of machine learning algorithms for understanding data.

While there are some formulae and computational elements to the course, the emphasis is on applications of acquired concepts to “real life” of research scientists. 

Though the vast majority of what you will learn in this course can be applied in any software package, the seminar will mostly use R for empirical examples and exercises. 


<!-- After completing the course, you will: -->

<!-- + ~~Know the technical and substantive difference between fixed and random effects.~~ -->
<!-- Understand random intercepts and random coefficients and know when to use each one.~~ -->
<!-- + ~~Know how to combine the strengths of random-effects and fixed effects approaches into a single model.~~ -->
<!-- + ~~Know how to estimate these models and interpret the results.~~ -->


# Schedule

```{r sched}

library (tibble)
library (kableExtra)
library(stringr)

schedule <- tibble::tribble(
   ~Day,            ~Time,            ~Activity, ~Location,
   "24 July, 2024", "9am - 12am", "Lesson 1 ~ Working with data (in R)",  "Building ??, Room ?",
   "\"\"", "2pm - 5pm", "Practice Session 1",   "Building ??, Room ?",

      "25 July, 2024", "9am - 12am", "Lesson 2 ~ Inference",  "Building ??, Room ?",
   "\"\"", "2pm - 5pm", "Practice Session 2", "Building ??, Room ?",

      "26 July, 2024", "9am - 12am", "Lesson 3 ~ Modeling correlation and regression",  "Building ??, Room ?",
   "\"\"", "2pm - 5pm", "Practice Session 3",  "Building ??, Room ?",

      "27 July, 2024", "9am - 12am", "Lesson 4 ~ Intro to machine learning",  "Building ??, Room ?",
   "\"\"", "2pm - 5pm", "Practice Session 4", "Building ??, Room ?")

schedule %>% 
 kbl(caption = "Tentative Schedule") %>% 
  column_spec(c(1,3), bold = ifelse( str_detect(schedule$Activity, "~", negate = FALSE), TRUE, FALSE)) %>% 
  collapse_rows(columns = 1, valign = "middle", target = 1) %>% 
  kable_styling()
```
 
Hot & cold drinks will be served during the morning breaks.

# Practical information

Please, do bring your laptop as no computer will be available.  

# Acknowledgements

The materials presented in this workshops have been prepared drawing from various sources: 

* ccc
* mmm
* xxxx

<!-- # TEST  -->
<!-- [Download "*.R" file](practice/Rcode/labs_day1.R) -->

<!-- ## License -->

<!-- The work presented in this website is licensed under a {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}} {{< fa brands creative-commons-sa >}} [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/), except for the borrowed and mentioned with proper *"Source:"* statements. -->

<!-- ## Materials -->

<!-- This source code and license for all of the materials on this website can be found on a dedicated Github repo [{{< fa brands github >}}](https://github.com/Lulliter/R4biostats). -->