
# (Install) & Load R Packages --------------------------------------------------
options(scipen = 999)

library(fs)        # file/directory interactions
library(here)      # tools find your project's files, based on working directory
library(janitor)   # tools for examining and cleaning data
library(skimr)     # tools for summary statistics 
library(dplyr)     # {tidyverse} tools for manipulating and summarising tidy data 
library(forcats)   # {tidyverse} tool for handling factors
library(tidyr)
library(broom)

library(ggplot2)   # {tidyverse} tools for plotting
#library(ggridges)  # alternative to plot density functions 
library(ggthemes)
library(RColorBrewer) 
library(gridExtra)
library(kableExtra)
library(data.table)


# Load dataset ------------------------------------------------------------
# Use `here` in specifying all the subfolders AFTER the working directory 
heart_failure <- read.csv(file = here("practice", "data_input", "02_datasets", "heart_failure_clinical_records_dataset.csv"), 
                             header = TRUE, # 1st line is the name of the variables
                             sep = ",", # which is the field separator character.
                             na.strings = c("?"),  # specific values I want R to interpret as missing, i.e. NA
                             row.names = NULL) 



# Following  EDA | ML | urv Analy --------------------------------------------------------------
# FANGYA https://www.kaggle.com/code/fangya/machine-learning-survival-for-heart-failure

# dataset 299 heart failure patients collected at the Faisalabad Insti- tute of Cardiology and at the Allied Hospital in Faisalabad (Punjab, Pakistan), during April–December 2015

# Understanding variables ------------------------------------------------------

# Variable Categorization to make the lab values more accessible to clinical doctors, we will categorize them respect to standard practices.

# Ejection Fraction (proportion of blood pumped out of the heart during a single contraction) A normal ejection fraction is about 50% to 75%, according to the American Heart Association.: 
  # + borderline 41%  50%.A borderline ejection fraction  
  # + Normal 50%- 75%, 
  # + Abnormal <41% or >75%  

# Serum Creatinine (waste product generated by creatine: well known in the literature as a major driver of heart failure [57–62], and also a key biomarker in renal dysfunction): 
  # + For adult men, 0.74 to 1.35 mg/dL (65.4 to 119.3 micromoles/L) 
  # + For adult women, 0.59 to 1.04 mg/dL (52.2 to 91.9 micromoles/L)

# Creatinine Phosphokinase (states the level of the CPK enzyme in blood. When a muscle tissue gets damaged, CPK flows into the blood. Therefore, high levels of CPK in the blood of a patient might indicate a heart failure or injury):
  # + 10 to 120 micrograms per liter (mcg/L)

# Platelets: A normal platelet count ranges from 150,000 to 450,000 platelets per microliter of blood.
 
# Serum Sodium (Sodium is a min- eral that serves for the correct functioning of muscles and nerves.): 
  # + A normal blood sodium level is between 135 and 145 milliequivalents per liter (mEq/L)
 
# Death Event: states if the patient died or survived before the end of the follow-up period, that was 130 days on aver- age 
  # + death event = 1 96  --- EVENT: Patient who died. 
  # + death event = 0 203 --- CENSOR: Patient is alive
 
# Age Group: Age <65 years old, Age >=65 years old


 

# Data table  -------------------------------------------------------------


# Recode  variables -----------------------------------------------------------------
heart <- heart_failure

# Assign ID
heart$id <- seq.int(nrow(heart))

# Assign Character value to Numeric variables
heart$sex_c <-ifelse(heart$sex==1, "Male", "Female")
heart$smoking_c <-ifelse(heart$smoking==1, "Yes", "No")
heart$high_blood_pressure_c <- ifelse(heart$high_blood_pressure==1, "Yes","No")
heart$diabetes_c <-ifelse(heart$diabetes==1, "Yes", "No")
heart$anaemiac_c <- ifelse(heart$anaemia==1 ,"Yes", "No")

# Platelets : Hopkins Medicine
heart$plat_c <- ifelse(heart$platelets>150000 & heart$platelets <450000, "Platelets Normal", "Platelets Abnormal")
heart$plat_d <- ifelse(heart$platelets>150000 & heart$platelets <450000, 0,1)
heart$plat_norm <- heart$platelets/1000

# Serum Sodium: Mayo Clinic
heart$serum_sodium_c <- ifelse(heart$serum_sodium >135 & heart$serum_sodium<145, "Serum Sodium Normal", "Serum Sodium Abnormal")
heart$serum_sodium_d <- ifelse(heart$serum_sodium >135 & heart$serum_sodium<145, 0, 1)

# Creatine Phosphkinase : Mountsinai
heart$cpk_c <- ifelse(heart$creatinine_phosphokinase >10 & heart$creatinine_phosphokinase<120, 
                      "CPK Normal", "CPK Abnormal")
heart$cpk_d <- ifelse(heart$creatinine_phosphokinase >10 & heart$creatinine_phosphokinase<120, 
                      0, 1)

# ejection_fraction: Mayo
heart$efraction_c <-ifelse(heart$ejection_fraction<=75 & heart$ejection_fraction>=41, "Ejection Normal", "Ejection Abnormal")
heart$efraction_d <-ifelse(heart$ejection_fraction<=75 & heart$ejection_fraction>=41, 0, 1)

#serum_creatinine :mayo
heart$sercreat_c<- ifelse((heart$serum_creatinine<1.35 & heart$serum_creatinine>0.74 & heart$sex==1 ) | 
                        (heart$serum_creatinine<1.04 &heart$serum_creatinine>0.59 & heart$sex==0) ,
                      "Creatinine Normal", "Creatinine Abnormal"   )

heart$sercreat_d <- ifelse((heart$serum_creatinine<1.35 & heart$serum_creatinine>0.74 & heart$sex==1 ) |
                         (heart$serum_creatinine<1.04 & heart$serum_creatinine>0.59 & heart$sex==0) , 0, 1 )

#age group: Pharma convention  
heart$age65_c <- ifelse( heart$age<65, "Age <65", "Age >=65")
heart$age_65_d <- ifelse( heart$age<65, 0, 1)

#event vs censor
heart$censor_c <- ifelse(heart$DEATH_EVENT==0, "Censor", "Event")


# Recode as factor  -------------------------------------------------------
f_features = c("DEATH_EVENT","anaemiac_c", "diabetes_c", "high_blood_pressure_c", "sex_c", "smoking_c", "censor_c")
 
heart <- heart %>%
  mutate_at(f_features, as.factor) %>% 
  # Reorder the column name alphabetically 
  select(order(colnames(.))) %>% 
  relocate (censor_c, .after = DEATH_EVENT) %>% 
  relocate (id, .before = everything())


# _________--------------------------------------------------------------


# Visualizaton numeric features ---------------------------------------------------------------------
# FANGYA https://www.kaggle.com/code/fangya/machine-learning-survival-for-heart-failure
# YWenLin https://www.kaggle.com/code/ywhenlyn/heart-attack-visualization-modelling#Data-Exploration-&-Visualisation

  #!  # UdaySheel Zupudi https://www.kaggle.com/code/shootboyxxx/heart-attack-eda-and-modeling
heart_failure$DEATH_EVENT <- factor(heart_failure$DEATH_EVENT)


#####  --- age -----------------------------------------------------------------
# As the age increases, probability of death event increases as shown 


a<-ggplot(heart_failure,aes(x = age))+
  geom_histogram(binwidth = 5, color = "white", fill = "grey",alpha = 0.5)+
  theme_fivethirtyeight()+
  labs(title = "Age Distribution", caption = "i. Age Distribution")+
  theme(plot.caption = element_text(hjust = 0.5,face = "italic"))+
  scale_x_continuous(breaks = seq(40,100,10))

b<-ggplot(heart_failure,aes(x = age, fill = DEATH_EVENT))+
  geom_histogram(binwidth = 5, position = "identity",alpha = 0.5,color = "white")+
  theme_fivethirtyeight()+
  scale_fill_manual(values = c("#999999", "#d8717b"))+
  labs(caption = "ii. Age Distribution with Death Event")+
  theme(plot.caption = element_text(hjust = 0.5,face = "italic"))+
  scale_x_continuous(breaks = seq(40,100,10))

gridExtra::grid.arrange(a,b)

#####  --- CPK -----------------------------------------------------------------
# Creatinine Phosphokinase (states the level of the CPK enzyme in blood. When a muscle tissue gets damaged, CPK flows into the blood. Therefore, high levels of CPK in the blood of a patient might indicate a heart failure or injury)
# Although the distribution for the death event and non death event are similar average creatinine for the death event is slightly higher than for the non death event * 57% chances of death where creatinine greater than 4000

heart_failure %>% 
  group_by(DEATH_EVENT) %>% 
  summarise(
    N = n(),
    mean_age = mean(age),
    mean_cpk = mean(creatinine_phosphokinase))

a <- ggplot(heart_failure,aes(x = creatinine_phosphokinase))+
  geom_density(fill = "gray", alpha = 0.5)+
  theme_fivethirtyeight()+
  labs(title = "Distribution of creatinine phosphokinase", caption = "i. Density distribution")+
  theme(plot.caption = element_text(hjust = 0.5, face = "italic"))

b <- ggplot(heart_failure,aes(x = creatinine_phosphokinase,fill = DEATH_EVENT))+
  geom_density(alpha = 0.5)+theme_fivethirtyeight()+
  scale_fill_manual(values = c("#999999", "#d8717b"))+
  geom_vline(aes(xintercept = mean(creatinine_phosphokinase[DEATH_EVENT == 0])), color = "gray")+
  geom_vline(aes(xintercept = mean(creatinine_phosphokinase[DEATH_EVENT==1])), color = "#d8717b")+
  geom_curve(xend = 540, yend = 0.0009, x = 2000, y = 0.0014, 
             arrow = arrow(length = unit(0.2,"cm")),
             linewidth = 0.5,
             color = "gray")+
  geom_curve(xend = 670, yend = 0.0013, x = 2000, y = 0.0016, 
             arrow = arrow(length = unit(0.2,"cm")),
             linewidth = 0.5, color = "#d8717b")+
  geom_text(label = "mean for non death events", x = 2000, y = 0.0014,size = 2.5)+
  geom_text(label = "mean for death events", x = 2000, y = 0.0016,size = 2.5)+
  labs(caption = "ii. Density distribution with events of death",x = "creatinine kinase")+
  theme(plot.caption = element_text(hjust = 0.5, face = "italic"))+
  annotate("text",x = 4000, y = 0.0010, label = "For creatinine >= 4000 \n57% chances of death")

gridExtra::grid.arrange(a,b)

#####  --- Ejection Fraction -----------------------------------------------------------------
# Ejection Fraction (proportion of blood pumped out of the heart during a single contraction) A normal ejection fraction is about 50% to 75%, according to the American Heart Association.: 
# + borderline 41%  50%.A borderline ejection fraction  
# + Normal 50%- 75%, 
# + Abnormal <41% or >75%  


heart_failure %>% 
  group_by(DEATH_EVENT) %>% 
  summarise(
    N = n(),
    mean_ejection_fraction = mean(ejection_fraction),
    median_ejection_fraction = median(ejection_fraction))


a<-ggplot(heart_failure, aes(x = ejection_fraction))+
  geom_density(fill = "gray", alpha = 0.5)+
  theme_fivethirtyeight()+
  geom_vline(xintercept = 50, linetype = "dashed")+
  geom_vline(xintercept = 70, linetype = "dashed")+
  scale_x_continuous(breaks = seq(20,80,10))+
  annotate("text",x = 60, y = 0.03, label = "Normal Function", color  = "darkgreen")+
  annotate("text", x = 78, y = 0.03, label = "High Function", color = "#e68000")+
  annotate("text", x = 35, y = 0.03, label = "Low Function", color = "darkred")+
  labs(title = "Distribution of Ejection Fraction", caption = "i. Distribution of ejection fraction")+
  theme(plot.caption = element_text(hjust = 0.5, face = "italic"))

b<-ggplot(heart_failure, aes(x = ejection_fraction, fill = DEATH_EVENT))+
  geom_density(alpha = 0.5)+
  theme_fivethirtyeight()+
  scale_fill_manual(values = c("#999999", "#d8717b"))+
  scale_x_continuous(breaks = seq(20,80,10))+
  geom_vline(aes(xintercept = mean(ejection_fraction[DEATH_EVENT == 0])), color = "grey33")+
  geom_vline(aes(xintercept = mean(ejection_fraction[DEATH_EVENT == 1])), color = "goldenrod1")+
  geom_curve(aes(xend = mean(ejection_fraction[DEATH_EVENT == 0])), 
             y = 0.05, x = 50, yend  = 0.04, 
             arrow = arrow(length = unit(0.2,"cm")),color = "black")+
  geom_curve(aes(xend = mean(ejection_fraction[DEATH_EVENT == 1])), 
             x = 27,yend= 0.04, y = 0.05, 
             arrow = arrow(length = unit(0.2,"cm")), color = "black")+
  annotate("text", x = 50, y = 0.048, label = "mean for non death events", size = 2.5)+
  annotate("text", x = 27, y = 0.052, label = "mean for death events", size = 2.5)+
  geom_vline(xintercept = 50, linetype = "dashed")+
  geom_vline(xintercept = 70, linetype = "dashed")+
  theme(plot.caption = element_text(hjust = 0.5, face = "italic"))+
  labs(caption = "ii. Distribution of ejection fraction with death event")

gridExtra::grid.arrange(a,b)

#Ejection Fraction is notably lower where there is a death event

#####  --- Platelets -----------------------------------------------------------------
# Platelets play an important role in the processes of coagulation, inflammation, and immune response. The platelet count is routinely used to analyze bone marrow function, classify patients with blood loss, and identify syndromes characterized by thrombocytopenia and thrombocytosis. 

# A normal platelet count ranges from 150,000 to 450,000 platelets per microliter of blood.
a<-ggplot(heart_failure, aes(x = platelets))+
  geom_density(fill = "gray", alpha = 0.5)+
  theme_fivethirtyeight()+
  geom_vline(xintercept = 150000, linetype = "dashed")+
  geom_vline(xintercept = 400000, linetype = "dashed")+
  annotate("text",x = 300000, y = 0.000004, label = "Normal Count", color  = "darkgreen")+
  annotate("text", x = 600000, y = 0.000004, label = "High Count", color = "#e68000")+
  annotate("text", x = 70000, y = 0.000004, label = "Low Count", color = "darkred")+
  labs(title = "Distribution of Platelets", caption = "i. Distribution of platelets")+
  theme(plot.caption = element_text(hjust = 0.5, face = "italic"))

b<-ggplot(heart_failure, aes(x = platelets, fill = DEATH_EVENT))+
  geom_density(alpha = 0.5)+
  theme_fivethirtyeight()+
  scale_fill_manual(values = c("#999999", "#d8717b"))+
  #scale_x_continuous(breaks = seq(20,80,10))+
  geom_vline(aes(xintercept = mean(platelets[DEATH_EVENT == 0])), color = "grey33")+
  geom_vline(aes(xintercept = mean(platelets[DEATH_EVENT == 1])), color = "goldenrod1")+
  geom_curve(aes(xend = mean(platelets[DEATH_EVENT == 0])), yend = 0.000004, x = 350000, y  = 0.000005, arrow = arrow(length = unit(0.2,"cm")),color = "black")+
  geom_curve(aes(xend = mean(platelets[DEATH_EVENT == 1])), x = 170000,yend= 0.0000045, y = 0.000005, arrow = arrow(length = unit(0.2,"cm")), color = "black")+
  annotate("text", x = 400000, y = 0.000005, label = "mean for non death events", size = 2.5)+
  annotate("text", x = 170000, y = 0.000005, label = "mean for death events", size = 2.5)+
  geom_vline(xintercept = 150000, linetype = "dashed")+
  geom_vline(xintercept = 400000, linetype = "dashed")+
  theme(plot.caption = element_text(hjust = 0.5, face = "italic"))+
  labs(caption = "ii. Distribution of platelets with death event")


gridExtra::grid.arrange(a,b)

#####  --- Serum Creatinine -----------------------------------------------------------------
# Serum Creatinine (waste product generated by creatine: well known in the literature as a major driver of heart failure [57–62], and also a key biomarker in renal dysfunction): 
  # + For adult men, 0.74 to 1.35 mg/dL (65.4 to 119.3 micromoles/L) 
  # + For adult women, 0.59 to 1.04 mg/dL (52.2 to 91.9 micromoles/L)

a <- ggplot(heart_failure, aes(x = serum_creatinine))+
  geom_density(fill = "gray", alpha = 0.5)+
  theme_fivethirtyeight()+
  geom_vline(xintercept = 0.84, linetype = "dashed")+
  geom_vline(xintercept = 1.4, linetype = "dashed")+
  annotate("text",x = 1.05, y = 0.5, label = "Normal", color  = "darkgreen", angle = 90)+
  annotate("text", x = 3, y = 0.5, label = "Possible kidney \nmalfunction", color = "#e68000")+
  #annotate("text", x = 70000, y = 0.000004, label = "Low Count", color = "darkred")+
  labs(title = "Distribution of Serum Creatinine", caption = "i. Distribution of serum_creatinine")+
  theme(plot.caption = element_text(hjust = 0.5, face = "italic"))

b <- ggplot(heart_failure, aes(x = serum_creatinine, fill = DEATH_EVENT))+
  geom_density(alpha = 0.5)+
  theme_fivethirtyeight()+
  scale_fill_manual(values = c("#999999", "#d8717b"))+
  #scale_x_continuous(breaks = seq(20,80,10))+
  geom_vline(aes(xintercept = mean(serum_creatinine[DEATH_EVENT == 0])), color = "grey33")+
  geom_vline(aes(xintercept = mean(serum_creatinine[DEATH_EVENT == 1])), color = "goldenrod1")+
  geom_curve(aes(xend = mean(serum_creatinine[DEATH_EVENT == 0])), yend = 0.9, x = 2.5, y  = 1.25, arrow = arrow(length = unit(0.2,"cm")),color = "black")+
  geom_curve(aes(xend = mean(serum_creatinine[DEATH_EVENT == 1])), x = 3,yend= 0.5, y = 0.9, arrow = arrow(length = unit(0.2,"cm")), color = "black")+
  annotate("text", x = 2.5, y = 1.2, label = "mean for non death events", size = 2.5)+
  annotate("text", x = 3, y = 0.85, label = "mean for death events", size = 2.5)+
  geom_vline(xintercept = 0.84, linetype = "dashed")+
  geom_vline(xintercept = 1.4, linetype = "dashed")+
  theme(plot.caption = element_text(hjust = 0.5, face = "italic"))+
  labs(caption = "ii. Distribution of creatinine with death event")+
  annotate("text",label = "For creatinine > 2.5 \n60% chances of death", x = 5, y = 0.5)

gridExtra::grid.arrange(a,b)

#####  --- Serum Sodium -----------------------------------------------------------------
# (Sodium is a min- eral that serves for the correct functioning of muscles and nerves.): 
# + A normal blood sodium level is between 135 and 145 milliequivalents per liter (mEq/L)

a<-ggplot(heart_failure, aes(x = serum_sodium))+geom_density(fill = "gray", alpha = 0.5)+theme_fivethirtyeight()+
  geom_vline(xintercept = 135, linetype = "dashed")+
  geom_vline(xintercept = 145, linetype = "dashed")+
  annotate("text",x = 142, y = 0.08, label = "Normal concentr.", color  = "darkgreen")+
  annotate("text", x = 120, y = 0.08, label = "Possible Heart \nfailure", color = "darkred")+
  #annotate("text", x = 70000, y = 0.000004, label = "Low Count", color = "darkred")+
  labs(title = "Distribution of Serum Sodium", caption = "i. Distribution of serum_sodium")+
  theme(plot.caption = element_text(hjust = 0.5, face = "italic"))+
  scale_y_continuous(breaks = seq(0,0.1,0.05))

b<-ggplot(heart_failure, aes(x = serum_sodium, fill = DEATH_EVENT))+geom_density(alpha = 0.5)+theme_fivethirtyeight()+
  scale_fill_manual(values = c("#999999", "#d8717b"))+
  #scale_x_continuous(breaks = seq(20,80,10))+
  geom_vline(aes(xintercept = mean(serum_sodium[DEATH_EVENT == 0])), color = "grey33")+
  geom_vline(aes(xintercept = mean(serum_sodium[DEATH_EVENT == 1])), color = "goldenrod1")+
  geom_curve(aes(xend = mean(serum_sodium[DEATH_EVENT == 0])), yend = 0.04, x = 142, y  = 0.06, arrow = arrow(length = unit(0.2,"cm")),color = "black")+
  geom_curve(aes(xend = mean(serum_sodium[DEATH_EVENT == 1])), x = 139,yend= 0.06, y = 0.09, arrow = arrow(length = unit(0.2,"cm")), color = "black")+
  annotate("text", x = 142, y = 0.058, label = "mean for non death events", size = 2.5)+
  annotate("text", x = 139, y = 0.088, label = "mean for death events", size = 2.5)+
  geom_vline(xintercept = 135, linetype = "dashed")+
  geom_vline(xintercept = 145, linetype = "dashed")+
  theme(plot.caption = element_text(hjust = 0.5, face = "italic"))+
  labs(caption = "ii. Distribution of sodium with death event")
#annotate("text",label = "For creatinine > 2.5 \n60% chances of death", x = 5, y = 0.5)

gridExtra::grid.arrange(a,b)

# Visualizaton categorical features ---------------------------------------------------------------------
anem <- ggplot(heart, aes(x = DEATH_EVENT, fill = anaemiac_c))+
  geom_bar(position = "dodge")+
  theme_fivethirtyeight() +
  scale_x_discrete(labels  = c("Death Event:No","Death Event:Yes"))+
  scale_fill_manual(values = c("#999999", "#d8717b"), name = "Anaemia",
                    labels = c("No","Yes"))+
  labs(subtitle = "Anemia",x = "New x label" )
anem


diab <-ggplot(heart, aes(x = DEATH_EVENT, fill = diabetes_c))+
  geom_bar(position = "dodge")+
  theme_fivethirtyeight()+
  scale_x_discrete(labels  = c("Death Event:No","Death Event:Yes"))+
  scale_fill_manual(values = c("#999999", "#d8717b"), name = "Diabetes", 
                    labels = c("No","Yes"))+
  labs(subtitle = "Diabetes")
diab 

hbp <-ggplot(heart, aes(x = DEATH_EVENT, fill = high_blood_pressure_c))+
  geom_bar(position = "dodge")+
  theme_fivethirtyeight()+
  scale_x_discrete(labels  = c("Death Event:No","Death Event:Yes"))+
  scale_fill_manual(values = c("#999999", "#d8717b"), name = "High BP", labels = c("No","Yes"))+
  labs(subtitle = "High BP")
hbp 

sex <-ggplot(heart, aes(x = DEATH_EVENT, fill = sex_c))+
  geom_bar(position = "dodge")+
  theme_fivethirtyeight()+
  scale_x_discrete(labels  = c("Death Event:No","Death Event:Yes"))+
  scale_fill_manual(values = c("#999999", "#d8717b"), name = "Sex", labels = c("Female","Male"))+
  labs(subtitle = "Sex of patient")
sex 

table(heart$age65_c)
age65_c <-ggplot(heart, aes(x = DEATH_EVENT, fill = age65_c))+
  geom_bar(position = "dodge")+
  theme_fivethirtyeight()+
  scale_x_discrete(labels  = c("Death Event:No","Death Event:Yes"))+
  scale_fill_manual(values = c("#999999", "#d8717b"), name = "Age", labels = c("Age <65","Age >=65"))+
  labs(subtitle = "Age > 65")
age65_c 

smoke <-ggplot(heart, aes(x = DEATH_EVENT, fill = smoking_c))+
  geom_bar(position = "dodge")+
  theme_fivethirtyeight()+
  scale_x_discrete(labels  = c("Death Event:No","Death Event:Yes"))+
  scale_fill_manual(values = c("#999999", "#d8717b"), name = "Smoking", labels = c("No","Yes"))+
  labs(subtitle = "Smoking")
smoke 

grid.arrange(a,b,c,d,e)

# _________--------------------------------------------------------------

# Statistical testing  ----------------------------------------------------
#### FOR numerical features V death testing-----------------------------------------------
# Parametrico x camp indep (confronta le medie) -- the *t-test* is one of the best way to undersant the mean difference by feature between heart     failure group and no heart failure group.
# NON parametrico (confronta i ranghi) -- *Wilcoxon-Mann-Whitney*

    # Python ma BELLO https://www.kaggle.com/code/justicevil/visualization-statistical-test-prediction

# 1 sample Z-test, known sigma (PLATELETS) ------------------------------------------------------
# Reference 
# https://pulmonarychronicles.com/index.php/pulmonarychronicles/article/view/558/1223

# TPL in study US 17,969 adults measured in 103/µL
ref_pl_mu <- 236
ref_pl_sigma <- 59

heart %>% 
  ggplot(aes(x = plat_norm))+
  geom_histogram(aes(y = ..density..), bins=30, 
                 alpha=0.25, colour = "#4c4c4c", fill = "#85239b")+
  geom_density(colour = "#9b8423" ) + 
   theme_bw() + 
  labs(y = "Density", x = "Platelet count ( x 1000/µL)") 



#####  ---  A mano  --------------------------------------------
# https://cs.ioc.ee/ITKStat/files/9_hypothesis.pdf
mu <- 236 # GEneral POpulation of reference 
sigma  <- 59

# SAMPLE HF patients
n <- 299
x__HF <- mean(heart$plat_norm)                 #    263.358
s_HF <- sd(heart$plat_norm)                    #    97.80424

# IF large sample UNKNOWN sigma
std_err_HF_1 <- s_HF /sqrt(n-1)                    #    5.6656
z_stat_HF_1 <-  (x__HF - mu) / std_err_HF_1        # 4.8287

# IF large sample KNOWN sigma
std_err_HF <- sigma /sqrt(n)                    # 3.412058
z_stat_HF <-  (x__HF - mu) / std_err_HF        # 8.018043


# To find the p-value associated with a z-score in R, we can use the pnorm() function, which uses the following syntax:

      # q: The z-score
      # mean: The mean of the normal distribution. Default is 0.
      # sd: The standard deviation of the normal distribution. Default is 1.
      # lower.tail: If TRUE, the probability to the left of q in the normal distribution is returned           # . If FALSE, the probability to the right is returned. Default is TRUE.

pnorm(z_stat_HF, mean = 0, sd = 1, 
      lower.tail = TRUE) # Left-tailed test

pnorm(z_stat_HF, mean = 0, sd = 1, 
      lower.tail = FALSE) # Right-tailed test

2*pnorm(z_stat_HF, mean = 0, sd = 1, 
      lower.tail = FALSE) # Two-tailed test 0.00000000000000107443

# SAMPLING DISTRIBUTION SIMULATON 
# Let's take a SRS of size n = 64
set.seed(64)
# sub_sample 1 std err  + Z stat 
sample_64_1 <-  slice_sample(heart, n = 64, replace = FALSE)
sample_pl_mu_1 <- mean(sample_64_1$plat_norm) # mu_0 260.3733
sample_pl_sigma_1 <- sd(sample_64_1$plat_norm) #sigma_o 96.53336

std_err_1 <- heart_pl_sigma/sqrt(64) # 12.22553
z_stat_1 <-  (sample_pl_mu_1 - heart_pl_mu) / std_err_1 # -0.2441404
  
# sub_sample 2 std err  + Z stat   
sample_64_2 <-  slice_sample(heart, n = 64, replace = FALSE)
sample_pl_mu_2 <- mean(sample_64_2$plat_norm) # mu_0 265.7668
sample_pl_sigma_2 <- sd(sample_64_2$plat_norm) #sigma_o 81.59953

std_err_2 <- heart_pl_sigma/sqrt(64) # 12.22553
z_stat_2 <-  (sample_pl_mu_2 - heart_pl_mu) / std_err_2 # 0.1970265

# sub_sample 3 std err  + Z stat   
sample_64_3 <-  slice_sample(heart, n = 64, replace = FALSE)
sample_pl_mu_3 <- mean(sample_64_3$plat_norm) # mu_0 265.1842
sample_pl_sigma_3 <- sd(sample_64_3$plat_norm) #sigma_o 103.3775

std_err_3 <- heart_pl_sigma/sqrt(64) # 12.22553
z_stat_3 <-  (sample_pl_mu_3 - heart_pl_mu) / std_err_3 # 0.1493753

  
# 1 sample t-test, SMALL n known sigma (PLATELETS) ------------------------------------------------------
# Let's consider a hypothetical situation where my sample was smaller 
# Using the same dataset I apply a cutoff period of follow-up visit happening in <30 days 

mu <- 236 # GEneral POpulation of reference 
sigma  <- 59



# SAMPLE HF patients followw up less 30 days 
heart_30d <- heart %>% 
  filter(time < 30) # 35 obs 

n_30d <- nrow(heart_30d) # 35
x__HF_30d <- mean(heart_30d$plat_norm)                 #    252.2981
s_HF_30d <- sd(heart_30d$plat_norm)                    #    93.2949

# IF large sample UNKNOWN sigma
std_err_HF_1_30d <- s_HF_30d /sqrt(n-1)                    # 5.404429
t_stat_HF_1_30d <-  (x__HF_30d - mu) / std_err_HF_1_30d   # 3.015686

df <- n_30d-1   # 34 (approximate at 30) 

# To find the p-value associated with a t-score in R, we can use  pt(q, df, lower.tail = TRUE)

# q: The t-score
# df: df 
# lower.tail: 
    # + TRUE --> then we are going to calculate the probability to the left of q which is called as left-tailed test 
    # + FALSE.  Which is called as right-tailed test.


pt(t_stat_HF_1_30d, df, lower.tail = TRUE) # Left-tailed test

pt(t_stat_HF_1_30d, df, lower.tail = FALSE) # Right-tailed test

p_value_t_test <- 2*pt(t_stat_HF_1_30d, df, lower.tail = FALSE) # Two-tailed test 0.004825284


# IF large sample KNOWN sigma
# std_err_HF_30d <- sigma /sqrt(n)                       # 3.412058
# z_stat_HF_30d <-  (x__HF_30d - mu) / std_err_HF_30d    # 4.776607


# >>>>>> QUI  -------------------------------------------------------------


# 1 sample t-test age ------------------------------------------------------
# Literature Pakistan mean/median age in 2015 = 21

# QUESTION: TEST IF THE MEAN OF OUR SAMPLE IS DIFFERENT FROM THE POPULATION PARAMETER
# H0: THERE IS NO DIFFERENCE
# H1 MY SAMPLE X_ > mu

heart %>% 
  mutate(age_median = median(age))

t.test(heart$age, mu = 21, alternative = "greater")


# PARAM: 2 sample means T TEST ------------------------------------------------------
# (I use Platelets bc the density plots seems Normal) 
# (A normal platelet count ranges from 150,000 to 450,000 platelets per microliter of blood)
# https://r-training.pages.uni.lu/biostat1/lectures/Compare_samples.html#6
# https://www.statology.org/variance-ratio-test-in-r/


# Assumptions 4 Student's t test: Comparing two means
    # 1. Independence  --> presumed bc they are all different people ?!?!
    # 2. Similar variances (homoskedasticity) --->> Check!
    # 3. Normality    --> visually check 
    # (Errors must be normally distribute)

# First, check the assumptions

###### A2 Compare var between 2 samples (BY HAND) ---------
# Fisher's F test
# var.test(sample1, sample2)
# # Divide the larger variance by the smaller one
# # Example: compare the variances of garden A & C

var_plat_dead <- var(heart$platelets[heart$DEATH_EVENT == 1])
n_dead <- nrow(heart[heart$DEATH_EVENT == 1,])
var_plat_alive <- var(heart$platelets[heart$DEATH_EVENT == 0])
n_alive <- nrow(heart[heart$DEATH_EVENT == 0,])

# If the variances in the groups are the same, this ratio should be close to 1.0
F.ratio <- var_plat_dead / var_plat_alive
F.ratio  # 1.020497 
# If the variances in the groups are the same, this ratio should be close to 1.0

# F distribution with df=(n−1,n−1)
  # The F distribution is defined only for non-negative values
  # The F distribution is not symmetric.

# Variance test 
# Define the critical value of F distribution for a risk of alpha=0.05
qf(0.975, df1 = n_dead-1, df2 = n_alive-1) # critical value  1.398723
# Compute the exact p-value
2 * (1 - pf(F.ratio, df1 = (n_dead-1), df2 = (n_alive-1)))
# 0.8914982

###### A2 Compare var between 2 samples (R function) ---------
var.test(heart$platelets[heart$DEATH_EVENT == 1] , heart$platelets[heart$DEATH_EVENT == 0])
    # F.ratio  # 1.020497 
    # p-value = 0.8915
    # 95% CI of ration [0.7295918 1.4589660]
    # I conclude Vars are the same ~ (Fail to reject H0 = The population variances are equal)


###### A3 Normality (R function) ---------
library(broom)
tidy(shapiro.test(heart$platelets[heart$DEATH_EVENT == 1]))
tidy(shapiro.test(heart$platelets[heart$DEATH_EVENT == 0]))



######  2 samples t test (by hand) ---------
# Step 1 - compute difference of sample means
diff <- mean(heart$platelets[heart$DEATH_EVENT == 1]) - mean(heart$platelets[heart$DEATH_EVENT == 0])
diff # -10276.45

# Step 2 - Compute associated t-statistics
t <- diff / (sqrt( (var_plat_dead / n_dead) + (var_plat_alive / n_alive)))
t # -0.8447853   # sign does not matter, how many df?


# Step 3 - degrees of freedom
# n1 + n2 - number of estimated parameters (2 means)
degrfred <- n_dead + n_alive - 1 - 1 # 297

# Step 4 - Deduced p-value
2 * pt(t, df = degrfred) #  0.3989107

######  2 samples t test (R function) ---------
# With Welch correction (on by default) Unequal variance is compensated by lowering df
t.test(heart$platelets[heart$DEATH_EVENT == 1], 
       heart$platelets[heart$DEATH_EVENT == 0],
       var.equal = FALSE) # df = 184.79

# Without Welch correction
t.test(heart$platelets[heart$DEATH_EVENT == 1], 
       heart$platelets[heart$DEATH_EVENT == 0],
       var.equal = TRUE) # df = 297


# _________--------------------------------------------------------------
# NON PARAM: 2 sample means Mann-Whitney / Wilcoxon ----------------------------
# Recall conditions 

####### ___ 1. Independence  --> VIOLATED --------------------------
# e.g. The Independence assumption is violated when the samples share more than they should | Two samples from a same individual
# (PARAM): 2 sample means *PAIRED *t-test  ----------------------------
 
####### ___ 2. Similar variances (homoskedasticity) --->> VIOLATED -------

####### ___ 3. Normality    --> VIOLATED -------
####### ___CPK (a mano)  ----------------------------------------------------

# e.g. When the errors are not normally distributed e.g. creatinine_phosphokinase
library(broom)

# 1/2 Shapiro-Wilk Normality Test to verify normality 
tidy(shapiro.test(heart$creatinine_phosphokinase)) # not normal 
tidy(shapiro.test(heart$creatinine_phosphokinase[heart$DEATH_EVENT == 1]))
tidy(shapiro.test(heart$creatinine_phosphokinase[heart$DEATH_EVENT == 0]))

# 2/2  2sample Wilcoxon-Mann-Whitney test
    # The hypothesis define as:
    # H0: The mean value of specific feature between the death group and no death group is equal.
    # H1: The mean value of specific feature between the death group and no death group is not equal.

heart |> # go for long format
  pivot_longer(cols = c(creatinine_phosphokinase),
               names_to = "death_cpk", values_to = "cpk_value") |> 
    mutate(rank = rank(cpk_value, ties.method = "average")) |> 
  # do the grouping AFTER ranking
  group_by(DEATH_EVENT) |>
  summarise(n_patients = n(),
            rank_sum_statistic =   sum(rank))

# Wilcoxon rank sum statistic obtained from samples with size n1 and n2
qwilcox(0.975, m = 203, n = 96) # 11111
# Compare this critical value to the 2 sum(rank)
# If one of sum is higher than 11111 then we reject H0
# Groups dead /alive have different means


####### ___CPK (R function )  ----------------------------------------------------
# res <- wilcox.test(creatinine_phosphokinase ~ DEATH_EVENT, # immagino 0, 1
#                    data = heart ,
#                    exact = FALSE, alternative = "two.sided" )
# res$p.value 

res_less <- wilcox.test(creatinine_phosphokinase ~ DEATH_EVENT, # immagino 0, 1
                   data = heart ,
                   exact = FALSE, alternative = "less") # ! 
res_less$p.value 

# res_more <- wilcox.test(creatinine_phosphokinase ~ DEATH_EVENT, # immagino 0, 1
#                    data = heart ,
#                    exact = FALSE, alternative = "greater")
# res_more$p.value 

# The p-value of the test is 0.684, which is more than the significance level alpha = 0.05. We can conclude that creatinine_phosphokinase level is NOT significantly different between survived and dead patients with a p-value = 0.684


####### ___CPK (Compare Non-parametric versus parametric) ----------------------------
bind_rows(
  tidy(wilcox.test(
    heart$creatinine_phosphokinase[heart$DEATH_EVENT == 1],
    heart$creatinine_phosphokinase[heart$DEATH_EVENT == 0])),
  tidy(t.test(
    heart$creatinine_phosphokinase[heart$DEATH_EVENT == 1],
    heart$creatinine_phosphokinase[heart$DEATH_EVENT == 0])))
# --> p.value Non-parametric tests are more conservative with less power

#####  --- Ejection Fraction -----------------------------------------------------------------
# siccome dal grafico NON mi sembra che abbia andamento normale uso  U di Mann Whitney
res <- wilcox.test(ejection_fraction ~ DEATH_EVENT, # immagino 0, 1
                   data = heart ,
                   exact = FALSE, alternative = "two.sided" )
res
res$p.value
format(res$p.value, scientific=F)
 

#### FOR categorical features V death testing   ----------------------------------------------------
The hypothesis define as:
  
  H0: The relationship between the following feature against heart_failure is independent
H1: The relationship between the following feature against heart_failure is not independent -------
  
  
# 2 sample t test  --------------------------------------------------------
# https://rpubs.com/haroldchoi/677496

E.g. understand is there statistical difference in the age of Male and Female of which have a higher chance of heart attack.
The heart dataset is filtered for individuals who have a high likelihood of heart attack.

# 1) test normality 
# 2) test Test homogeneity of variance
# 3) Student t test


# _________--------------------------------------------------------------

# Possible correlation between two numeric columns? -----------------------
# https://gexijin.github.io/learnR/the-heart-attack-data-set-i.html#possible-correlation-between-two-numeric-columns



#  Correlation Between Serum Cholesterol and Maximum Heart Rate -----------
https://eportfolio.utm.my/user/muhammad-haziq-bin-sulaiman/project-1
Based on the scatter plot between the two variables Serum cholesterol and Maximum heart rate shown above, the points on the graph appears to be random and the two variables have no dependency with each other. There is also no linear relationship between the two variables. The correlation coefficient is calculated in RStudio using the cor() function.

The value of the correlation coefficient is very close to zero and therefore the strength of the correlation coefficient is very weak. The value is consistent with the features seen in the scatter plot and thus it can be concluded that higher level of serum cholesterol does not lead to higher heart rate of a heart disease patient.

H0 : ρ = 0 (no linear correlation)

H1 : ρ != 0(linear correlation exists)

α = 0.05

For the significance test for correlation, the function cor.test() is used in RStudio. The significance level of the test is 0.05.

# 2 sample t test  v2 --------------------------------------------------------
# https://eportfolio.utm.my/user/muhammad-haziq-bin-sulaiman/project-2-hypothesis-testing-on-attributes-of-heart-disease-patients
the hypothesis testing is done to test if there are any difference between the mean blood pressure of patients aged above 55 and mean blood pressure of patients aged 55 and below. 
+ The null hypothesis is the mean between the two groups are the same and 
+ the alternative hypothesis is the mean has different values. The significance level for this test is 0.05 and the variance are assumed to be unequal.

calculate calculate the critical and test t value. The value of tval is the  value while t.alpha is t critical value. Therefore, we have  = 4.793 and t = ±1.968 since the test is two-tailed.

# 2 sample t test  --------------------------------------------------------
# 


# Chicco e Jurman tests -----------
We used common univariate tests such as 

+ **Mann–Whitney U test**  - applied to each feature in relation to the death event target, detects whether we can reject the null hypothesis that the distribution of the each feature for the groups of samples defined by death event are the same. A low p-value of this test (close to 0) means that the ana- lyzed feature strongly relates to death event, while a high p-value (close to 1) means the opposite. 

+ **Pearson correlation coefficient** (or Pearson product-moment correla- tion coefficient, PCC) [86] indicates the linear correlation between elements of two lists, showing the same elements on different positions. The absolute value of PCC generates a high value (close to 1) if the elements of the two lists have linear correlation, and a low value (close to 0) otherwise.
  
+ chi square test [87] between two fea- tures checks how likely an observed distribution is due to chance [89]. A low p-value (close to 0) means that the two features have a strong relation; a high p-value (close to 1) means, instead, that the null hypothesis of independence cannot be discarded.

+ plus the Shapiro–Wilk test [88] to assess if each feature was extracted from a normal distribution.


# Pearson’s correlation coefficients (PPC), which is given by
cor.test(AGE, LOS)
# Spearman’s rank correlation coefficient ρ is a non-parametric measure of correlation
cor.test(AGE, LOS, method = "spearman")




# Associations between categorical variables? -----------------------------
# https://rpubs.com/haroldchoi/677496
E.g. H0: Likelihood that heart attack and gender are related.
H1: Likelihood that heart attack and gender are not related.

contingency table 
chisq.test(counts)


# Associations between a categorical and a numeric variables? -------------

ggplot 
scatterplot 


# multiple linear regression. ---------------------------------------------


# Normalization and Data Splitting ----------------------------------------


# ML  ---------------------------------------------------------------------
# Chicco e Jurman 
Regarding machine learning feature ranking, we focused only on Random Forests [72, 91], because as it turned out to be the top performing clas- sifier on the complete dataset (“Feature ranking results” section).
# https://rpubs.com/USL/798455